# bow-redis default values
name: redis
version: "7"
replicas: 1
storage: 5Gi
storage_class: null

password_secret: null  # null = no password

resources:
  cpu: "100m"
  memory: "128Mi"
  limits_cpu: "200m"
  limits_memory: "256Mi"

service:
  port: 6379
  type: ClusterIP

persistence:
  enabled: true

config:
  maxmemory: "128mb"
  maxmemory_policy: "allkeys-lru"
