# bow-redmine default values
name: redmine
version: "5.1"
replicas: 1
storage: 30Gi
storage_class: null

service:
  port: 3000
  type: ClusterIP

resources:
  cpu: "250m"
  memory: "256Mi"
  limits_cpu: "500m"
  limits_memory: "512Mi"

ingress:
  enabled: false
  host: null
  tls: false
  ingress_class: nginx

# Dependency: PostgreSQL
postgresql:
  enabled: true
  name: redmine-db
  database: redmine
  credentials_secret: redmine-db-credentials
  storage: 20Gi
  resources:
    cpu: "250m"
    memory: "256Mi"
    limits_cpu: "500m"
    limits_memory: "512Mi"
